### ISSUE TITLE
Minor bugs (but quite a dangerous one)

### ISSUE THREAD

**Issue by niklashed** [Miker2808/PyRoboteq#2]
Hey, nice job and thanks for sharing! I found some bugs when trying out the lib:

* EM_STOP command does not work due to missing '!':  https://github.com/Miker2808/PyRoboteq/blob/68206820cb7bfac46264399e395969bac2356c37/PyRoboteq/roboteq_commands.py#L23

* When sending command, a plus should not be included. This is probably a typo, and it seems to work anyway since the controller probably disregards the extra '+' : https://github.com/Miker2808/PyRoboteq/blob/68206820cb7bfac46264399e395969bac2356c37/PyRoboteq/roboteq_handler.py#L60

**Comment by Miker2808** [comment]
Thanks for pointing out the issues.
I corrected the EM_STOP typo.
As for the plus sign, I kept it.
When I just started with this little project that I made simply to make my life a little easier working with these controllers.
One of the issues that I had and made me completely redesign the handler, especially the loop inside the reading commands method, is that I had the controller failing when sending commands in high frequency. Not sure if this version is included in the git but back then you had a "sleep(10)" because of that. adding the plus sign and some changes in returns allowed me to remove the need to limit the script by freezing it after every iteration.
Therefore, unless it is a game changing/ dangerous issue I'll not change it.
